/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.JDialog;
import javax.swing.text.TabableView;
import logica.ListaAlumnos;


/**
 *
 * @author PabloTejedorRivadull
 */
public class MenuPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form MenÃºPrincipal
     */
    private PantallaPrincipal pantallaPrincipal;
    public ListaAlumnos listaAlumnos = new ListaAlumnos();
    
    public MenuPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        parent.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneAlumnos_Empresas = new javax.swing.JScrollPane();
        jTableAlumnos_Empresas = new javax.swing.JTable();
        jButtonCerrarSesion = new javax.swing.JButton();
        jMenuBarInicio = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemTablaAlum = new javax.swing.JMenuItem();
        jMenuItemFormAlum = new javax.swing.JMenuItem();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemTablaEmp = new javax.swing.JMenuItem();
        jMenuItemFormEmp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableAlumnos_Empresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAlumnos_Empresas.setViewportView(jTableAlumnos_Empresas);

        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jMenuPrincipal.setText("Menú");

        jMenuAlumnos.setText("Alumnos");

        jMenuItemTablaAlum.setText("Tabla de Alumnos");
        jMenuItemTablaAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemTablaAlum);

        jMenuItemFormAlum.setText("Formulario de Alumnos");
        jMenuItemFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemFormAlum);

        jMenuPrincipal.add(jMenuAlumnos);

        jMenuEmpresa.setText("Empresas");

        jMenuItemTablaEmp.setText("Tabla de Empresas");
        jMenuItemTablaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaEmpActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jMenuItemTablaEmp);

        jMenuItemFormEmp.setText("Formulario Empresas");
        jMenuItemFormEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormEmpActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jMenuItemFormEmp);

        jMenuPrincipal.add(jMenuEmpresa);

        jMenuBarInicio.add(jMenuPrincipal);

        setJMenuBar(jMenuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jScrollPaneAlumnos_Empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCerrarSesion)
                .addGap(2, 2, 2)
                .addComponent(jScrollPaneAlumnos_Empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTablaAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaAlumActionPerformed
        TablaAlumnos tablaAlumnos = new TablaAlumnos(this, false);
        tablaAlumnos.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaAlumActionPerformed

    private void jMenuItemFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormAlumActionPerformed
        FormularioAlumnos formularioAlum = new FormularioAlumnos(pantallaPrincipal, false);
        formularioAlum.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormAlumActionPerformed

    private void jMenuItemTablaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaEmpActionPerformed
        TablaEmpresas tablaEmpresas = new TablaEmpresas(this, false);
        tablaEmpresas.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaEmpActionPerformed

    private void jMenuItemFormEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormEmpActionPerformed
        FormularioEmpresas formularioEmp = new FormularioEmpresas(pantallaPrincipal, false);
        formularioEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormEmpActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        new PantallaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBarInicio;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenuItem jMenuItemFormAlum;
    private javax.swing.JMenuItem jMenuItemFormEmp;
    private javax.swing.JMenuItem jMenuItemTablaAlum;
    private javax.swing.JMenuItem jMenuItemTablaEmp;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPaneAlumnos_Empresas;
    private javax.swing.JTable jTableAlumnos_Empresas;
    // End of variables declaration//GEN-END:variables
}
