/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author PabloTejedorRivadull
 */
public class TablaEmpresas extends javax.swing.JDialog {

    /**
     * Creates new form TablaEmpresas
     */
    private PantallaPrincipal pantallaPrincipal;
    
    public TablaEmpresas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarInicio = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemTablaAlum = new javax.swing.JMenuItem();
        jMenuItemFormAlum = new javax.swing.JMenuItem();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemTablaEmp = new javax.swing.JMenuItem();
        jMenuItemFormEmp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuPrincipal.setText("Menú");

        jMenuAlumnos.setText("Alumnos");

        jMenuItemTablaAlum.setText("Tabla de Alumnos");
        jMenuItemTablaAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemTablaAlum);

        jMenuItemFormAlum.setText("Formulario de Alumnos");
        jMenuItemFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemFormAlum);

        jMenuPrincipal.add(jMenuAlumnos);

        jMenuEmpresa.setText("Empresas");

        jMenuItemTablaEmp.setText("Tabla de Empresas");
        jMenuItemTablaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaEmpActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jMenuItemTablaEmp);

        jMenuItemFormEmp.setText("Formulario Empresas");
        jMenuItemFormEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormEmpActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jMenuItemFormEmp);

        jMenuPrincipal.add(jMenuEmpresa);

        jMenuBarInicio.add(jMenuPrincipal);

        setJMenuBar(jMenuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTablaAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaAlumActionPerformed
        TablaAlumnos tablaAlumnos = new TablaAlumnos(pantallaPrincipal, true);
        tablaAlumnos.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaAlumActionPerformed

    private void jMenuItemFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormAlumActionPerformed
        FormularioAlumnos formularioAlum = new FormularioAlumnos(pantallaPrincipal, true);
        formularioAlum.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormAlumActionPerformed

    private void jMenuItemTablaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaEmpActionPerformed
        TablaEmpresas tablaEmpresas = new TablaEmpresas(pantallaPrincipal, true);
        tablaEmpresas.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaEmpActionPerformed

    private void jMenuItemFormEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormEmpActionPerformed
        FormularioEmpresas formularioEmp = new FormularioEmpresas(pantallaPrincipal, true);
        formularioEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaEmpresas dialog = new TablaEmpresas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBarInicio;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenuItem jMenuItemFormAlum;
    private javax.swing.JMenuItem jMenuItemFormEmp;
    private javax.swing.JMenuItem jMenuItemTablaAlum;
    private javax.swing.JMenuItem jMenuItemTablaEmp;
    private javax.swing.JMenu jMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
