/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import gui.tablemodel.EmpresaTableModel;
import logica.ListaEmpresas;

/**
 *
 * @author PabloTejedorRivadull
 */
public class TablaEmpresas extends javax.swing.JDialog {

    /**
     * Creates new form TablaEmpresas
     */
    private PantallaPrincipal pantallaPrincipal;
    private ListaEmpresas listaEmpresas = new ListaEmpresas();
    
    public TablaEmpresas(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTableEmpresas.setModel(new EmpresaTableModel(listaEmpresas.getListaEmpresas()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();
        jMenuBarInicio = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemTablaAlum = new javax.swing.JMenuItem();
        jMenuItemFormAlum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpresas);

        jMenuPrincipal.setText("Menú");

        jMenuInicio.setText("Inicio");

        jMenuItemInicio.setText("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemInicio);

        jMenuPrincipal.add(jMenuInicio);

        jMenuAlumnos.setText("Alumnos");

        jMenuItemTablaAlum.setText("Tabla de Alumnos");
        jMenuItemTablaAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemTablaAlum);

        jMenuItemFormAlum.setText("Formulario de Alumnos");
        jMenuItemFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormAlumActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemFormAlum);

        jMenuPrincipal.add(jMenuAlumnos);

        jMenuBarInicio.add(jMenuPrincipal);

        setJMenuBar(jMenuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTablaAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaAlumActionPerformed
        TablaAlumnos tablaAlumnos = new TablaAlumnos(this, true);
        tablaAlumnos.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaAlumActionPerformed

    private void jMenuItemFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormAlumActionPerformed
        FormularioAlumnos formularioAlum = new FormularioAlumnos(pantallaPrincipal, true);
        formularioAlum.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormAlumActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        MenuPrincipal menu = new MenuPrincipal(pantallaPrincipal, false);
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBarInicio;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemFormAlum;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemTablaAlum;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresas;
    // End of variables declaration//GEN-END:variables
}
