/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import gui.tablemodel.AlumnosTableModel;
import logica.ListaAlumnos;

/**
 *
 * @author PabloTejedorRivadull
 */
public class TablaAlumnos extends javax.swing.JDialog {
    
    private PantallaPrincipal pantallaPrincipal;
    private ListaAlumnos listaUsuarios = new ListaAlumnos();

    /**
     * Creates new form TablaUsuarios
     */
    public TablaAlumnos(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        jTableUsuarios.setModel(new AlumnosTableModel(listaUsuarios.getListaUsuarios()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTableUsuarios = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jMenuBarInicio = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuEmpesas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTableUsuarios.setViewportView(jTableUsuarios);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jMenuInicio.setText("Inicio");
        jMenuBarInicio.add(jMenuInicio);

        jMenuEmpesas.setText("Empresas");
        jMenuBarInicio.add(jMenuEmpesas);

        setJMenuBar(jMenuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPaneTableUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPaneTableUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JMenuBar jMenuBarInicio;
    private javax.swing.JMenu jMenuEmpesas;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JScrollPane jScrollPaneTableUsuarios;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
